"""Configuration for the coordinated-behaviour domain pack.

A social platform: accounts, the topics they post about, the devices they post
from, and the follows, posts, reshares and replies between them. Inside it,
labelled **campaigns**: groups of accounts acting together, some of them
inauthentic and some of them not.

Why the decoys matter more here than in the fraud pack
-----------------------------------------------------
Laundering has a weak legitimate twin: a payroll fan-out really does look like
a mule fan-out, but most fan-ins in a bank are not suspicious and a detector
that flags all of them is obviously wrong. Coordinated behaviour has a *strong*
legitimate twin. A fandom reacting to an album drop, a city reacting to an
earthquake, and a paid amplification ring are all, structurally, the same
thing: a burst of near-simultaneous, near-identical activity from a tightly
connected group.

So a coordination dataset whose only labelled structures are inauthentic is
worse than useless: any detector that fires on synchrony scores perfectly, and
that is exactly the detector that ruins real platforms by suspending fan clubs
and protest movements. Here the organic bursts are generated by the same
machinery as the campaigns, labelled ``is_coordinated=False``, and counted as
false positives when flagged. ``decoy_ratio`` is 1.0 at ``tradecraft="high"``:
as many organic structures as inauthentic ones.

``tradecraft`` is the hardness dial. Like the fraud pack's, it is an input to a
measurement rather than an assertion: :func:`..hardness.hardness_report` scores
what a single-feature detector can still see at each level.
"""

from __future__ import annotations

import datetime as dt
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from graphfaker.schema.patterns import Camouflage, PatternCatalog, PatternSpec

Tradecraft = Literal["low", "medium", "high"]

#: Base sizes at scale 1.0. A platform sees far more events per account than a
#: bank sees transactions per account, hence the ratio.
BASE_ACCOUNTS = 5_000_000
BASE_EVENTS = 100_000_000
BASE_CAMPAIGNS = 1_000

#: Inauthentic playbooks, in the order campaigns are allocated. Each is a
#: coordination *shape* documented in the open literature on influence
#: operations; none of them is a recipe for running one, and none of them
#: generates message content beyond a template id.
#: What the pack injects: the eight inauthentic playbooks with their share of
#: the campaign budget and their natural span in days before
#: ``timing_jitter_hours`` stretches it, then the three organic decoys, each
#: naming the playbook it imitates. The order is the order campaigns are
#: allocated and injected, and a seed only reproduces a dataset because of it.
#:
#: Each playbook is a coordination *shape* documented in the open literature
#: on influence operations; none of them is a recipe for running one, and none
#: generates message content beyond a template id.
CATALOG = PatternCatalog(
    base=BASE_CAMPAIGNS,
    floor=2,
    patterns=[
        PatternSpec(name="copypasta", share=0.16, span_days=0.05),
        PatternSpec(name="amplification_ring", share=0.16, span_days=0.2),
        PatternSpec(name="reply_brigade", share=0.12, span_days=0.1),
        PatternSpec(name="follow_farm", share=0.12, span_days=2.0),
        PatternSpec(name="hashtag_flood", share=0.14, span_days=0.3),
        PatternSpec(name="sockpuppet_cluster", share=0.12, span_days=5.0),
        PatternSpec(name="astroturf_campaign", share=0.10, span_days=30.0),
        PatternSpec(name="account_handover", share=0.08, span_days=10.0),
        # The organic twins. A fandom reacting to a release and a paid
        # amplification ring are structurally the same thing, so a dataset
        # whose only labelled structures are inauthentic rewards any detector
        # that fires on synchrony, which is the detector that suspends fan
        # clubs. Each decoy is matched to the playbook it imitates on the
        # properties that are not the point, chiefly posting volume.
        PatternSpec(name="fandom_burst", imitates="hashtag_flood", span_days=0.3),
        PatternSpec(name="breaking_news", imitates="copypasta", span_days=0.15),
        PatternSpec(name="mutual_follow_community", imitates="follow_farm", span_days=20.0),
    ],
)

#: The inauthentic playbooks, in allocation order.
PLAYBOOKS = CATALOG.injected
#: The organic structures, which are labelled ``is_coordinated=False``.
DECOY_PLAYBOOKS = CATALOG.decoys
#: Which inauthentic playbook each decoy is the twin of, for the hardness
#: report: a decoy is only doing its job if it is hard to separate from its
#: twin.
DECOY_TWIN = CATALOG.twins


class TradecraftProfile(Camouflage):
    """What a tradecraft level does to injected campaigns.

    ``text_blend``: 0 leaves every account in a burst posting the same template
    id, which is the signature a duplicate-text detector is written to catch; 1
    draws template ids from the organic distribution of the topic, so text
    similarity alone carries nothing.

    ``timing_jitter_hours``: the window a campaign's events are spread over.
    Sub-minute synchrony is the classic tell and the easiest thing in the world
    to detect; real operations stagger.

    ``activity_camouflage``: fraction of campaign accounts that also carry
    organic activity at the population rate, so posting volume and topic
    breadth do not single them out.

    ``overlap``: probability a campaign reuses an account already in another,
    producing the overlapping clusters that make attribution hard.

    ``decoy_ratio``: organic structures with the same shape, as a fraction of
    the inauthentic campaign count. Labelled ``is_coordinated=False``.

    ``account_age_blend``: 0 creates every campaign account just before the
    campaign (a bloc of same-day signups is the single loudest signal in real
    platform data); 1 uses accounts aged like the population, which is what
    buying or farming aged accounts achieves.

    ``size_scale``: multiplier on campaign sizes.

        Degree is the signal hardness cannot blend away, and the fraud pack
        learned this the hard way: recruiting campaign members from the most
        active accounts was tried as camouflage and measured to do the
        opposite, because hubs are outliers already. The same holds here, so
        recruitment is uniform over eligible accounts and ``size_scale`` is the
        lever that keeps cluster size from being a giveaway.
    """

    #: How aged the campaign's accounts are. This dial is the platform's
    #: own: a bloc of same-day signups has no equivalent in a bank.
    account_age_blend: float = Field(ge=0.0, le=1.0)

    #: The shared dials are :class:`~graphfaker.schema.patterns.Camouflage`;
    #: these names are what a platform reader calls them. On a platform the
    #: signature is the text, so ``text_blend`` is the signature blend.
    @property
    def text_blend(self) -> float:
        return self.signature_blend

    @property
    def timing_jitter_hours(self) -> float:
        return self.timing_spread


TRADECRAFT_PROFILES: dict[str, TradecraftProfile] = {
    "low": TradecraftProfile(
        signature_blend=0.0,
        timing_spread=0.05,
        activity_camouflage=0.0,
        overlap=0.0,
        decoy_ratio=0.0,
        account_age_blend=0.0,
        size_scale=1.0,
    ),
    "medium": TradecraftProfile(
        signature_blend=0.5,
        timing_spread=6.0,
        activity_camouflage=0.6,
        overlap=0.2,
        decoy_ratio=0.5,
        account_age_blend=0.5,
        size_scale=0.75,
    ),
    "high": TradecraftProfile(
        signature_blend=0.9,
        timing_spread=72.0,
        activity_camouflage=1.0,
        overlap=0.4,
        decoy_ratio=1.0,
        account_age_blend=1.0,
        size_scale=0.5,
    ),
}



class CoordinationConfig(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    #: ``1.0`` = ~5M accounts / ~100M events.
    scale: float = Field(default=0.001, gt=0.0)
    tradecraft: Tradecraft = "medium"
    #: Activity period.
    period_start: dt.date = dt.date(2026, 1, 1)
    period_days: int = Field(default=90, ge=7)
    locale: str = "en_US"
    #: Latent interest communities; topics, attributes and who follows whom are
    #: conditioned on them.
    communities: int = Field(default=12, ge=1)
    #: Distinct topics (hashtags, subjects) accounts post about.
    topics: int | None = None
    #: Mean follows per account. Real platforms run into the hundreds; the
    #: default keeps the follow graph a similar size to the event stream so
    #: neither dominates a dataset.
    follows_per_account: int = Field(default=15, ge=0)
    #: Override campaigns per playbook. ``None`` derives them from scale.
    campaigns: dict[str, int] | None = None

    # ---------------------------------------------------------------- derived

    @property
    def num_accounts(self) -> int:
        return max(200, round(BASE_ACCOUNTS * self.scale))

    @property
    def num_topics(self) -> int:
        if self.topics is not None:
            return self.topics
        # Enough that a campaign pushing one topic is not automatically the
        # whole conversation, and at least a few per community.
        return max(4 * self.communities, int(self.num_accounts * 0.01))

    @property
    def num_devices(self) -> int:
        # Most accounts post from one device; sockpuppet clusters share.
        return max(150, int(self.num_accounts * 0.9))

    @property
    def num_follows(self) -> int:
        return self.num_accounts * self.follows_per_account

    @property
    def num_events(self) -> int:
        return max(4_000, round(BASE_EVENTS * self.scale))

    @property
    def num_campaigns(self) -> int:
        if self.campaigns is not None:
            return sum(self.campaigns.values())
        # At least two of every playbook, so a small dataset still covers the
        # catalogue.
        return CATALOG.total(self.scale)

    @property
    def campaign_counts(self) -> dict[str, int]:
        if self.campaigns is not None:
            return {name: self.campaigns.get(name, 0) for name in PLAYBOOKS}
        return CATALOG.counts(self.num_campaigns)

    @property
    def profile(self) -> TradecraftProfile:
        return TRADECRAFT_PROFILES[self.tradecraft]

    @property
    def period_end(self) -> dt.date:
        return self.period_start + dt.timedelta(days=self.period_days)

    @model_validator(mode="after")
    def _known_playbooks(self) -> CoordinationConfig:
        if self.campaigns:
            unknown = set(self.campaigns) - set(PLAYBOOKS)
            if unknown:
                raise ValueError(f"unknown playbooks: {sorted(unknown)}")
        return self
